const tabs=['Proyectos','Muros','Techo','Concreto','Acero','Tarrajeo','Enchapes','Pisos','Costos materiales','Presupuesto rápido','Cotización','Cotización libre'];
const S=JSON.parse(localStorage.getItem('obrapro_v4')||'{}');S.prices??={cemento:30,kingkong:1.6,pandereta:1.45,f58:60,f12:40,f38:24,f14:10.5,f8mm:17.5,a16:6.5,a8:7,arenaF:190,arenaG:190,hormigon:190,piedra:350,agua:35,clavo2:7,clavo25:7,clavo3:7,clavo35:7,clavo4:7};S.items??=[];S.contact??='956 308 104';const save=()=>localStorage.setItem('obrapro_v4',JSON.stringify(S));
const nav=document.querySelector('#nav'),main=document.querySelector('#main');tabs.forEach((t,i)=>{let b=document.createElement('button');b.textContent=t;b.onclick=()=>show(i);nav.append(b);let p=document.createElement('section');p.className='page';p.id='p'+i;main.append(p)});
function show(i){[...nav.children].forEach((b,j)=>b.classList.toggle('active',i==j));[...main.children].forEach((p,j)=>p.classList.toggle('active',i==j));render(i)}
const fld=(l,id,v='',type='number')=>`<label>${l}<input id="${id}" type="${type}" value="${v}"></label>`;const sel=(l,id,opts)=>`<label>${l}<select id="${id}">${opts.map(x=>`<option>${x}</option>`).join('')}</select></label>`;
function addItem(desc,qty,unit,price){S.items.push({desc,qty:+qty||0,unit,price:+price||0});save();alert('Partida agregada al presupuesto');}
function simpleCalc(title,fields,formula){return `<div class="card"><h2>${title}</h2><div class="grid">${fields}</div><p class="hint">Completa las medidas y agrega el resultado al presupuesto.</p><button class="primary" onclick="${formula}">Calcular y agregar</button></div>`}
function render(i){let p=document.querySelector('#p'+i);if(i===0)p.innerHTML=`<div class=card><h2>Proyectos guardados</h2>${fld('Nombre del proyecto','proj',S.project||'','text')}<br><button class=primary onclick="S.project=proj.value;save();alert('Proyecto guardado')">Guardar proyecto</button></div>`;
if(i===1)p.innerHTML=simpleCalc('Muros',fld('Largo (m)','ml')+fld('Alto (m)','mh')+sel('Ladrillo','mt',['King Kong','Pandereta'])+fld('Mano de obra S/ por m²','mmo',35),`(()=>{let a=+ml.value*+mh.value;let pr=mt.value==='King Kong'?S.prices.kingkong:S.prices.pandereta;addItem('Muro '+mt.value,a,'m²',(+mmo.value)+(pr*40))})()`);
if(i===2)p.innerHTML=simpleCalc('Techo',fld('Largo (m)','tl')+fld('Ancho (m)','ta')+fld('Espesor (m)','te',.2)+fld('Mano de obra S/ por m²','tmo',120),`(()=>{let a=+tl.value*+ta.value;addItem('Techo / losa',a,'m²',+tmo.value+(S.prices.cemento*1.1))})()`);
if(i===3)p.innerHTML=simpleCalc('Concreto',sel('Elemento','ct',['Columna','Viga','Losa maciza','Falso piso','Volumen general'])+fld('Largo (m)','cl')+fld('Ancho (m)','ca')+fld('Alto/Espesor (m)','ch'),`(()=>{let v=+cl.value*+ca.value*+ch.value;addItem('Concreto - '+ct.value,v,'m³',S.prices.cemento*8+S.prices.arenaG*.5+S.prices.piedra*.8)})()`);
if(i===4)p.innerHTML=simpleCalc('Acero',sel('Diámetro','ad',['5/8','1/2','3/8','1/4','8 mm'])+fld('Longitud total (m)','al')+fld('Merma (%)','am',5),`(()=>{let map={'5/8':S.prices.f58,'1/2':S.prices.f12,'3/8':S.prices.f38,'1/4':S.prices.f14,'8 mm':S.prices.f8mm};let bars=Math.ceil((+al.value*(1+(+am.value/100)))/9);addItem('Acero '+ad.value,bars,'barra 9 m',map[ad.value])})()`);
if(i===5)p.innerHTML=simpleCalc('Tarrajeo',fld('Largo (m)','trl')+fld('Alto (m)','trh')+fld('Caras','trc',1)+fld('Mano de obra S/ por m²','trmo',30),`(()=>{let a=+trl.value*+trh.value*+trc.value;addItem('Tarrajeo',a,'m²',+trmo.value+8)})()`);
if(i===6)p.innerHTML=simpleCalc('Enchapes',fld('Área (m²)','ea')+fld('Merma (%)','em',10)+fld('Mano de obra S/ por m²','emo',50)+fld('Material S/ por m²','ep',45),`(()=>{let a=+ea.value*(1+(+em.value/100));addItem('Enchape',a,'m²',+emo.value+ +ep.value)})()`);
if(i===7)p.innerHTML=simpleCalc('Pisos y contrapisos',fld('Área (m²)','pa')+fld('Espesor (m)','pe',.05)+fld('Mano de obra S/ por m²','pmo',30),`(()=>{addItem('Piso / contrapiso',+pa.value,'m²',+pmo.value+18)})()`);
if(i===8)renderPrices(p);if(i===9)renderBudget(p);if(i===10)renderQuote(p,false);if(i===11)renderQuote(p,true)}
function renderPrices(p){let q=S.prices;p.innerHTML=`<div class=card><h2>Costos de materiales</h2><p class=hint>Los precios son editables y se guardan en este dispositivo.</p><div class=grid3>${fld('Cemento 42.5 kg','cemento',q.cemento)}${fld('Ladrillo King Kong','kingkong',q.kingkong)}${fld('Ladrillo Pandereta','pandereta',q.pandereta)}${fld('Fierro 5/8”','f58',q.f58)}${fld('Fierro 1/2”','f12',q.f12)}${fld('Fierro 3/8”','f38',q.f38)}${fld('Fierro 1/4”','f14',q.f14)}${fld('Fierro 8 mm','f8mm',q.f8mm)}${fld('Alambre N.º 16 / kg','a16',q.a16)}${fld('Alambre N.º 8 / kg','a8',q.a8)}${fld('Arena fina / m³','arenaF',q.arenaF)}${fld('Arena gruesa / m³','arenaG',q.arenaG)}${fld('Hormigón / m³','hormigon',q.hormigon)}${fld('Piedra chancada / m³','piedra',q.piedra)}${fld('Agua / m³','agua',q.agua)}${fld('Clavo 2” / kg','clavo2',q.clavo2)}${fld('Clavo 2½” / kg','clavo25',q.clavo25)}${fld('Clavo 3” / kg','clavo3',q.clavo3)}${fld('Clavo 3½” / kg','clavo35',q.clavo35)}${fld('Clavo 4” / kg','clavo4',q.clavo4)}</div><br><button class=primary onclick="document.querySelectorAll('#p8 input').forEach(x=>S.prices[x.id]=+x.value);save();alert('Precios guardados')">Guardar precios</button></div>`}
function total(){return S.items.reduce((a,x)=>a+x.qty*x.price,0)}function renderBudget(p){p.innerHTML=`<div class=card><h2>Presupuesto rápido</h2>${table(S.items)}<p class=total>Total: S/ ${total().toFixed(2)}</p><button class=danger onclick="S.items=[];save();render(9)">Vaciar presupuesto</button></div>`}
function table(items,editable=false){return `<div style="overflow:auto"><table><thead><tr><th>Descripción</th><th>Cant.</th><th>Und.</th><th>P. unit.</th><th>Total</th>${editable?'<th></th>':''}</tr></thead><tbody>${items.map((x,k)=>`<tr><td>${x.desc}</td><td>${x.qty}</td><td>${x.unit}</td><td>S/ ${(+x.price).toFixed(2)}</td><td>S/ ${(x.qty*x.price).toFixed(2)}</td>${editable?`<td><button class=danger onclick="S.free.splice(${k},1);save();render(11)">×</button></td>`:''}</tr>`).join('')}</tbody></table></div>`}
function quoteFields(prefix){let d=S[prefix]??={cliente:'',proyecto:S.project||'',ubicacion:'',tiempo:'',fecha:new Date().toISOString().slice(0,10),vigencia:'15 días',obs:'',telefono:S.contact};S[prefix]=d;return `<div class=grid>${fld('Cliente',prefix+'cliente',d.cliente,'text')}${fld('Proyecto / obra',prefix+'proyecto',d.proyecto,'text')}${fld('Ubicación / referencia',prefix+'ubicacion',d.ubicacion,'text')}${fld('Tiempo estimado',prefix+'tiempo',d.tiempo,'text')}${fld('Fecha',prefix+'fecha',d.fecha,'date')}${fld('Vigencia',prefix+'vigencia',d.vigencia,'text')}${fld('Teléfono / WhatsApp',prefix+'telefono',d.telefono,'tel')}<label>Observaciones<textarea id="${prefix}obs">${d.obs}</textarea></label></div>`}
function sync(prefix){['cliente','proyecto','ubicacion','tiempo','fecha','vigencia','telefono','obs'].forEach(k=>S[prefix][k]=document.getElementById(prefix+k).value);save()}
function renderQuote(p,free){let key=free?'freeQuote':'autoQuote';S.free??=[];let items=free?S.free:S.items;p.innerHTML=`<div class="card no-print"><h2>${free?'Cotización libre':'Cotización automática'}</h2>${quoteFields(key)}${free?`<hr><div class=grid3>${fld('Descripción','fd','','text')}${fld('Cantidad','fq',1)}${fld('Unidad','fu','und','text')}${fld('Precio unitario S/','fp',0)}</div><br><button class="primary gold" onclick="S.free.push({desc:fd.value,qty:+fq.value,unit:fu.value,price:+fp.value});save();render(11)">Agregar partida</button>`:''}<br><button class=primary onclick="sync('${key}');render(${free?11:10})">Guardar datos</button> <button class="primary gold" onclick="sync('${key}');window.print()">Imprimir / Guardar PDF</button></div><div class=quote><img class=quote-logo src=logo-obrapro.png><h2>${free?'COTIZACIÓN LIBRE':'COTIZACIÓN'}</h2><p><b>Contacto:</b> ${S[key].telefono} &nbsp; | &nbsp; <b>Fecha:</b> ${S[key].fecha}</p><p><b>Cliente:</b> ${S[key].cliente||'—'}<br><b>Proyecto:</b> ${S[key].proyecto||'—'}<br><b>Ubicación:</b> ${S[key].ubicacion||'—'}<br><b>Tiempo estimado:</b> ${S[key].tiempo||'—'} &nbsp; | &nbsp; <b>Vigencia:</b> ${S[key].vigencia||'—'}</p>${table(items,free)}<p class=total>Total: S/ ${items.reduce((a,x)=>a+x.qty*x.price,0).toFixed(2)}</p><p><b>Observaciones:</b> ${S[key].obs||'—'}</p></div>`}
show(0);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
